
import { GoogleGenAI, GenerateContentResponse } from "@google/genai";
import { GenerationParams } from "../types";

export const generateFixImage = async (params: GenerationParams): Promise<string> => {
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY || '' });

  const prompt = `
    IMAGE BACKGROUND: Create a highly realistic, professional photo of ${params.backgroundPrompt}. 
    The atmosphere should be cinematic and high-quality.
    
    TEXT OVERLAY:
    Position: ${params.textPosition}
    Style: ${params.textStyle}
    
    1. Main Text: "${params.mainText}" 
       - Color: ${params.mainTextColor}
       - Style: Very large, bold, high-impact ${params.textStyle} font.
    2. Sub Text: "${params.subText}"
       - Color: ${params.subTextColor}
       - Style: Smaller, complementary ${params.textStyle} font directly below the main text.
    
    The text should be clearly legible. Use professional graphic design techniques like shadows, subtle glows, or semi-transparent backing if needed to ensure the text pops against the background.
    
    ${params.logo ? `BRANDING: At the bottom center or a professional corner of the image, seamlessly incorporate the provided logo image as a high-end branding element.` : ''}
    
    Final output should be a professional marketing visual or social media advertisement.
  `;

  const parts: any[] = [{ text: prompt }];

  if (params.logo && params.logoMimeType) {
    parts.push({
      inlineData: {
        data: params.logo.split(',')[1],
        mimeType: params.logoMimeType,
      },
    });
  }

  const response: GenerateContentResponse = await ai.models.generateContent({
    model: 'gemini-2.5-flash-image',
    contents: { parts },
  });

  const imagePart = response.candidates?.[0]?.content?.parts.find(p => p.inlineData);
  
  if (!imagePart || !imagePart.inlineData) {
    throw new Error("No image was generated by the model. Try refining your background prompt.");
  }

  return `data:${imagePart.inlineData.mimeType};base64,${imagePart.inlineData.data}`;
};
